name: cusp
version: git
summary: Cusp Daemon # 79 char long summary
description: |
  This snap provides the Cusp daemon cuspd and the command line
  tool cuspcli.
grade: stable
confinement: strict

apps:
    cuspd:
        command: bin/cuspd
        plugs: [home,network,network-bind]
    cuspcli:
        command: bin/cuspcli
        plugs: [home,network,network-bind,raw-usb]

parts:
  cusp:
    plugin: dump
    source: ./
    override-pull: |
        rootdir=$(pwd)
        gitroot=$(git rev-parse --show-toplevel)
        cd ${gitroot} && git archive \
            -o ${rootdir}/cusp-git.tar.gz \
            --format tar.gz -9 --prefix cusp-git/ HEAD
        cd ${rootdir}
        tar xf cusp-git.tar.gz ; rm -f cusp-git.tar.gz
        mkdir -p go/src/github.com/libonomy bin
        mv cusp-git/ go/src/github.com/evdatsion/cusp-sdk/

    build-snaps: [go]
    override-build: |
        base=`pwd`
        export GO111MODULE=on
        export GOPATH=`pwd`/go
        export GOBIN=$GOPATH/bin
        export PATH=$GOBIN:$PATH
        cd $GOPATH/src/github.com/evdatsion/cusp-sdk
        make go-mod-cache
        make tools
        make install
        mkdir $SNAPCRAFT_PART_INSTALL/bin
        cp $GOPATH/bin/cuspd $SNAPCRAFT_PART_INSTALL/bin
        cp $GOPATH/bin/cuspcli $SNAPCRAFT_PART_INSTALL/bin
